### ISSUE TITLE
leap of wheel turn value

### ISSUE THREAD

**Issue by VladSalat666** [nightmode/logitech-g29#13]
Hello

Could you add fix to lib?

If you will turn wheel slowly, you will observe leaps of wheel turn value, so I have fixed this issue
Just change this code:
`wheelCourse = wheelCourse / 255 * 99 // 99 instead of 100 so wheelCourse and wheelFine add up to 100% when they are both maxed out`
`wheelFine = wheelFine / 255`

on 

`wheelCourse = wheelCourse / 255 * ( 100 - ( 100 / 256 )) // 99 instead of 100 so wheelCourse and wheelFine add up to 100% when they are both maxed out`
`wheelFine = wheelFine / 255 * ( 100 / 256 ) // multiplied on this coefficient because of difference between an adjacent values is not 1`

in the data-map.js

**Comment by nightmode** [comment]
Hi Vlad,

This sounds great. I will pull my wheel out of storage tomorrow to test. ^_^

**Comment by VladSalat666** [comment]
I've created pull request with fix

**Comment by nightmode** [comment]
Pull request merged.

The wheel numbers have never looked so good. Thank you Vlad!

**Comment by nightmode** [comment]
I just made a 99% similar change to the logitech-g27 library for users of that older wheel system. Thanks again for not only reporting this issue but figuring out the fix for it too. Much appreciated. ^_^

**Comment by VladSalat666** [comment]
You are welcome!😉

**Comment by pipes80-collab** [comment]
my wheel no centered, who can help me?
