### ISSUE TITLE
my wheel not centered after autocentered

### ISSUE THREAD

**Issue by pipes80-collab** [nightmode/logitech-g29#15]
I have problem with my logitech g29, when start my debian system the wheel is not centered and not have force

**Comment by nightmode** [comment]
Hi Pipes,

Just in case, make sure your wheel's platform mode switch is set to PS3. The switch above the middle of the sheering wheel, and slightly back. There is a not so great picture of it in panel 1 of this PDF. https://www.logitech.com/assets/53755/3/g29-driving-force-racing-wheel.pdf

I find that my wheels tend to init after a reboot and once they are done, they use default autocentering but it sounds like your wheel just sits there after a reboot?

Does your wheel center once you use the logitech-g29 library?

**Comment by pipes80-collab** [comment]
Hello nightmode, my switch is on ps3 mode.
there are two autocentered, one after bios peripherical boot and one after OS peripherical boot, after OS peripherical boot my wheel not finish autocentered, I have try this time now

**Comment by nightmode** [comment]
If you have a Windows or Mac, try the wheel on there too. If the wheel does not autocenter on Windows and Mac, it might be an issue with the wheel itself.

For the older G27 wheel system, there were some special commands and resets you could do at the hardware level to change options by pressing / holding certain buttons. I'm not sure if the G29 has the same secret commands though.

**Comment by pipes80-collab** [comment]
My wheel work fine on Windows 10

**Comment by nightmode** [comment]
So without using the logitech-g29 library (this repo), your wheel autocenters ok in Wndows 10 but not Linux after a reboot?

Is your Linux machine a real linux machine or is a virtual machine hosted by a Windows or Mac? I've had weird issues inside virtual machines, especially with USB devices like the logitech wheel.

**Comment by pipes80-collab** [comment]
No, my machine Is not vittual

**Comment by nightmode** [comment]
How about when you do not use the repo. Does the wheel autocenter after a reboot?

**Comment by pipes80-collab** [comment]
Male autocentered bit Is not centered the wheel. I use you repo

**Comment by nightmode** [comment]
Without using the repo, does the wheel autocenter after a reboot?

**Comment by pipes80-collab** [comment]
I grave forget of work or not fine. Can i test and or disabile repo?

**Comment by nightmode** [comment]
I'm not sure what you mean. I'd love to have something I could look into for you but without steps to reproduce the problem (since it works on my linux machine) I'm kind of stuck and hoping you notice something in your own troubleshooting.

**Comment by pipes80-collab** [comment]
autocentered work with all mode and in other opeating system but not in debian.
I abandon the repo because it does not work as it should in my case.
Thank you for your work
