### ISSUE TITLE
Web HID support

### ISSUE THREAD

**Issue by joegaffey** [nightmode/logitech-g29#16]
Would you have any interest in adding suport for the upcoming Web HID standard for use in browsers?
https://wicg.github.io/webhid/
Its currently supported to some degree in Chrome behind a flag.

**Comment by nightmode** [comment]
Hi Joe. ^_^

I would LOVE to see the Logitech wheels connected to a browser. The amount of useful and non useful things you could mix together is exciting! Using the wheel with audio, video, games, navigation, or anything else in a  browser could lead to a lot of fun projects.

I am currently focused on Web Browser Extensions like [Sprucemarks](https://nightmode.fm/software/sprucemarks) for my Patreon supporters so I'm not sure when I can look into this but... my interest level is extremely high so thank you for suggesting this tech and opening this exploratory issue. :D

**Comment by joegaffey** [comment]
Glad to hear you're interested. I think some cool examples could help motivate browser devs to promote this API further.

Use cases I am thinking of are VR racing sims and mixed reality RC with real-time FPV video and accelerometer data for FFB over WebRTC.

I'm not sure how much is possible with current WebHID implementation though. Will try to get some time to dig into it further.

**Comment by nightmode** [comment]
Given the gift of so much time passing, I feel like WebHID is still very cool but perhaps out of scope for this library which is focused on Node.

Tiny bit more WebHID info at https://developer.mozilla.org/en-US/docs/Web/API/WebHID_API

Closing issue.

**Comment by razvanphp** [comment]
Hey, just want to mention that we are successfully using G29 (and other racing wheels) via WebHID in our Chrome-based racing game (using real cars).

Check out the teaser here: https://www.instagram.com/reel/DBtzMqDNg_T/

The only question if whether we can use the HID output reports to generate vibration, any hind on where to find those magic bits? Thanks!

**Comment by nightmode** [comment]
That is very cool looking. ^_^

I remember seeing some kind of C or C variant library from Logitech a long time ago but at the time I knew nothing about C so I could not explore it looking for any magic bits. I can only hope they have more examples or libraries out there nowadays but honestly have no idea. :o
