### ISSUE TITLE
on 'wheel-turn'，get no data

### ISSUE THREAD

**Issue by sjmlsxp** [nightmode/logitech-g29#17]
`device.on("data", function(data) {
        console.log('data: ', data);
}`

When I turn my G29, nothing console, but other events can.

env:
macOS 10.15.6
node v12.18.3

**Comment by nightmode** [comment]
I have a Mac with the same OS version so I'll install the same version of Node and try it out with the G29 a bit later today. I will let you know how it goes. ^_^

**Comment by nightmode** [comment]
Same macOS and Node version using the following script.

```js
const device = require('logitech-g29')

device.connect(function(err) {
    device.on('data', function(data) {
        console.log('data:', data)
    })
})
```
Turning the wheel all the way to the left logged `data: <Buffer 08 00 00 00 00 00 ff ff ff 75 81 9c>`

Leaving the wheel somewhere in the middle logged `data: <Buffer 08 00 00 00 82 81 ff ff ff 75 81 9c>`

Turning the wheel all the way to the right logged `data: <Buffer 08 00 00 00 ff ff ff ff ff 75 81 9c>`

From the buffers above, two sets of data go from `00 00` for left to `82 81` for center and then `ff ff` for right. That is what is supposed to happen anyway. :o

Is the wheel switch on the top of the middle section of your wheel set to PS3? It is hard to read but the PS3 option is when the switch is all the way to the left. If that switch is set to PS4 on the right side, weeeeeird things will happen.

If you can run the script above and still don't see data events when you turn your wheel... can you try the procedure below?

From a command prompt, go to the logitech-g29 library and then go into the `test` directory. Run `node test.js` and then you should get back human friendly events for everything you do on the wheel.

Please let me know how it goes. I am curious and I hope there is something easy to fix to get you back into doing whatever you want to do with the wheel. :D

**Comment by sjmlsxp** [comment]
Thanks, same one take off the power. But I don't know o(╯□╰)o
