### ISSUE TITLE
List of low level commands

### ISSUE THREAD

**Issue by wujekbrezniew** [nightmode/logitech-g29#19]
Hi,

Is there somewhere list of low level G29 commands?

**Comment by AxelAmbert** [comment]
> As what I'm doing is production stuff I will ask Logitech for list of low level commands and if they respond me (and won't mind of sharing this stuff publicly) i will create repo and link it here.

Hey, I would like to know if you have any news about this please? 🙂

**Comment by nightmode** [comment]
No news I am aware of. Hope things are going well for @wujekbrezniew which if we are really lucky, may lead to low level commands for the rest of us who are curious about those commands. ^_^

**Comment by nightmode** [comment]
Closing as there has been no news on this subject for a long time.
