### ISSUE TITLE
Customize steering wheel rotation Angle

### ISSUE THREAD

**Issue by LoveLife008** [nightmode/logitech-g29#20]
When I pass in a range of 180° through options, I can only go to 270°  . 
I hope you can help me deal with it. Could you relax the rotation Angle that can be customized  .
The initial determination is in the setRange function at line 222 of the index.js file

**Comment by nightmode** [comment]
Ah, I will need to get my wheel out of storage to test.

In the meantime, can you post the code you are using here? Where you are passing the options. That way I could use the same code once I get my wheel.

**Comment by LoveLife008** [comment]
Thank you very much for helping me solve the problem so late. I am very happy and wish you a happy Christmas Eve .
My test code is listed below, please help to have a look, if you need other support, please contact me in time, thank you very much !

`const JoyG29 = require('logitech-g29');
const exec = require('child_process').execFile;

// I have to start  Logitech G HUB to get wheel data.

function turnLogitechExe() {
    console.log("turn up Logitech G HUB!");
    let execCmd = exec("C:/Program Files/LGHUB/lghub.exe", function (err, data) {
        if (err) {
            console.log(err);
        }
    });
    execCmd.on('exit', (code) => {
        console.log(`get execCmd code: ${code}`);
    })
}
// turnLogitechExe();

// I need to set the G29 wheel Angle to only rotate 90° left and right.
const options = {
    autocenter: [1, 0.2],
    range: 180,
}

JoyG29.connect(options, function (error) {
    console.log('Ready')
})

JoyG29.on('changes', (data) => {
    console.log(`G29 data: ${data}`)
})

JoyG29.on('shifter-gear', (data) => {
    console.log('shifter-gear: ' + data);
})

JoyG29.on('error', (error) => {
    console.log(`G29 is error!`);
});`

**Comment by nightmode** [comment]
Sorry for the delay. I retrieved my Logitech wheels from storage today and hope to be able to test with them a bit later today.

**Comment by nightmode** [comment]
Good news. ^_^

I've been experimenting on my own local computer. I modified the `setRange` function in `code/index.js` line 222 to disable the 270 minimum range. The code below is what I disabled.

```
// if (options.range < 270) {
//     options.range = 270
// }
```

I then used the code below to test with.

```
const JoyG29 = require('logitech-g29');

const options = {
    autocenter: [1, 0.2],
    range: 180,
}

JoyG29.connect(options, function (error) {
    console.log('Ready')
})

JoyG29.on('changes', (data) => {
    console.log(data)
})

JoyG29.on('error', (error) => {
    console.log('Error', error);
});
```
The wheel does indeed report a full turn when rotated 90 degrees left or right. The wheel will resist turning more than 90 degrees but you can overpower it. I believe that is just how the Logitech wheel works. There is only a hard stop physically once you keep spinning the wheel in either direction.

So, I am not sure why I originally had a 270 degree minimum range set. Probably something I read in some specs somewhere or perhaps it was a limitation of the older G27 wheel that this G29 library came from. Either way, I will update the code and let you know once it is available here on GitHub and on NPM.

**Comment by nightmode** [comment]
Updated version `1.3.0` is live here on GitHub and also on NPM (https://www.npmjs.com/package/logitech-g29)

Please update your library to `1.3.0` and then try setting your range to 180 to get 90 degree turns on either side of the wheel. ^_^

**Comment by LoveLife008** [comment]
十分感谢，我今天升级到v1.3.0，使用方向盘测试正常，旋转角度已经能够达到180°.

**Comment by LoveLife008** [comment]
Thank you very much. Today, I upgraded to V1.3.0. The steering wheel test is normal, and the rotation Angle can reach 180°.

**Comment by nightmode** [comment]
Excellent. I will close this issue.

Happy coding. ^_^
