### ISSUE TITLE
Question Regarding Functionality

### ISSUE THREAD

**Issue by Raamzeez** [nightmode/logitech-g29#29]
Hello! I came across this repo earlier today and it looks very cool! I was just wondering, is there any way that I am able to give the steering wheel an angle and it can automatically turn to that direction? It doesn't seem to be a feature based on the docs - do you know if this is even possible? I was hoping there was a way to do it since I know the wheel can move to a position on it's own when it does calibration, but wasn't sure if there was a way to interface with it. Thanks!

**Comment by nightmode** [comment]
I have not heard of that capability to directly move the wheel to an angle but... I know of at least two projects in the past that people were using the force effects to move the wheel one way or another and when it got to a certain angle, reduce forces or try to hold that position. In one case it was an in-car project where someone wanted a Logitech wheel to mimic the angle of the real steering wheel. As far as I know, it worked but perhaps a bit of an unsupported use case. Oh and I think they key for that project was to have enough default friction on the wheel so it was not just bouncing back and forth, trying to keep an angle.

**Comment by Raamzeez** [comment]
Ah I see, yeah I was thinking there might be a possibility where the wheel could move at an angle using the force feedback, but it's not as elegant as I was hoping it would be. I might try it out though in the future, thanks for the help!
